import BalanceContainer from "./components/Balances/BalanceContainer";
import CreateAccount from "./components/CreateAccount";
import RestoreAccount from "./components/RestoreAccount";
import enterTransition from "./EnterTransition";
import InitError from "components/InitError";
import Certification from "components/platform/Certification";
import YoyowAccount from "components/platform/YoyowAccount";
import Contacts from "./components/Contacts/Contacts";
import Transfer from "./components/Transfer";
import History from "./components/History";
import SettingsContainer from "./components/Settings/SettingsContainer"
import Account from "./components/Settings/Account"
import ChangePassWord from "./components/Settings/ChangePassWord"
import ChangeAccountPassWord from "./components/Settings/ChangeAccountPassWord"
import ChangeWalletPassWord from "./components/Settings/ChangeWalletPassWord"
import OnAPIChange from "./components/Settings/OnAPIChange"
import ExampleForForm from "./components/Layout/ExampleForForm"
import BackupAccount from "./components/BackupAccount";
import ImportAccount from "./components/ImportAccount";
import ViewPurview from "./components/Settings/ViewPurview";
import RestoreWalletPwd from "./components/Settings/RestoreWalletPwd";
import ImportFile from "./components/Settings/ImportFile"
import ERC20Gateway from "./components/Balances/ERC20Gateway";
import Help from "./components/Help";
import AuthorizeService from "./components/AuthorizeService";
import Vote from "./components/Vote/Vote"
import Proxy from "./components/Vote/Proxy"